# Generated by Django 3.0 on 2020-03-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
