# Generated by Django 3.0 on 2020-03-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth1', '0002_delete_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
