# Generated by Django 3.0 on 2020-03-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0003_user_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Avatar',
        ),
    ]
