# Generated by Django 3.0 on 2020-03-20 21:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth1', '0005_user_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Profile',
            new_name='User_Avatar',
        ),
    ]
