# Generated by Django 3.0 on 2020-03-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0007_auto_20200320_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
