# Generated by Django 3.0 on 2020-03-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0008_auto_20200320_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
