# Generated by Django 3.0 on 2020-03-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
