# Generated by Django 3.0 on 2020-03-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_todomodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='name',
            field=models.CharField(default='No Name', max_length=30),
        ),
    ]
