# Generated by Django 3.0 on 2020-03-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0003_todomodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='data',
            field=models.TextField(),
        ),
    ]
