# Generated by Django 3.0 on 2020-03-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aradhya',
            options={'get_latest_by': 'date'},
        ),
        migrations.AddField(
            model_name='aradhya',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
