# Generated by Django 3.0 on 2020-03-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_api', '0002_auto_20200321_1308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aradhya',
        ),
    ]
